# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
     - constant_identifier_names # prefer
     - lines_longer_than_80_chars # avoid
     - package_api_docs # prefer
     - public_member_api_docs # prefer
     - unnecessary_const
     - avoid_catching_errors
     - avoid_print
     - avoid_void_async
     - cancel_subscriptions
     - cascade_invocations #https://dart-lang.github.io/linter/lints/cascade_invocations.html
     - leading_newlines_in_multiline_strings #https://dart-lang.github.io/linter/lints/leading_newlines_in_multiline_strings.html
     - only_throw_errors #https://dart-lang.github.io/linter/lints/only_throw_errors.html
     - prefer_const_constructors #https://dart-lang.github.io/linter/lints/prefer_const_constructors.html
     #- prefer_const_constructors_in_immutables #https://dart-lang.github.io/linter/lints/prefer_const_constructors_in_immutables.html
     - prefer_const_declarations #https://dart-lang.github.io/linter/lints/prefer_const_declarations.html
     - prefer_const_literals_to_create_immutables #https://dart-lang.github.io/linter/lints/prefer_const_literals_to_create_immutables.html

analyzer:
#   exclude:
#     - path/to/excluded/files/**
